/// Flutter icons Civil
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Civil
///      fonts:
///       - asset: fonts/Civil.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Civil {
  Civil._();

  static const _kFontFam = 'Civil';
  static const String  _kFontPkg = null;

  static const IconData crane = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engineer = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData excavator = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worker = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blueprint = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paintroller = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blueprint3 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelbarrow = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engineer1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graphic_design = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crane2 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engineer2 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brickwall = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house2 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crane1 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheel = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_repair = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tripod = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blueprint1 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steamroller = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blueprint2 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData concrete_mixer = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
